-- lua/plugins/theme.lua
-- Monokai Pro theme plugin spec for lazy.nvim
-- Loads early (priority 1000) so that dependent UI plugins can pick up the
-- palette automatically.

return {
  "loctvl842/monokai-pro.nvim",
  -- Load at startup so the colorscheme is ready before the UI draws
  lazy = false,
  priority = 1000,

  -- Optional UI dependency required for the :MonokaiProSelect picker
  dependencies = { "MunifTanjim/nui.nvim" },

  -- All user‑tweakable options live here; change these to taste.
  opts = {
    transparent_background = false,
    terminal_colors       = true,
    devicons              = true,  -- highlights nvim‑web‑devicons icons

    -- One of: "classic" | "octagon" | "pro" | "machine" | "ristretto" | "spectrum"
    filter = "pro",

    -- Auto‑switch preset at sunrise/sunset (requires localtime)
    day_night = {
      enable       = false,        -- set true to activate
      day_filter   = "pro",
      night_filter = "spectrum",
    },

    -- Syntax‑group font styles
    styles = {
      comment       = { italic = true },
      keyword       = { italic = true },
      type          = { italic = true },
      storageclass  = { italic = true },
      structure     = { italic = true },
      parameter     = { italic = true },
      annotation    = { italic = true },
      tag_attribute = { italic = true },
    },

    -- How incremental‑search highlights the current match: "underline" | "background"
    inc_search = "background",

    -- UI components whose background should blend with the editor
    background_clear = {
      "telescope",   -- Telescope prompt + results
      "toggleterm",  -- Terminal pop‑ups
      "neo-tree",    -- File explorer
      "notify",      -- nvim‑notify pop‑ups
      -- add "float_win" or others from README as desired
    },

    -- Per‑plugin tweaks
    plugins = {
      bufferline = {
        underline_selected = false,
        underline_visible  = false,
      },
      indent_blankline = {
        context_highlight       = "default", -- "default" | "pro"
        context_start_underline = false,
      },
    },

    ---------------------------------------------------------------------------
    -- Advanced hooks ---------------------------------------------------------
    ---------------------------------------------------------------------------

    ---@param c  Colorscheme               -- final hl table (read‑only)
    override = function(c) end,            -- tweak specific highlights

    ---@param cs Colorscheme               -- raw scheme generated by plugin
    ---@param p  ColorschemeOptions        -- palette tables
    ---@param cfg MonokaiProOptions        -- full user opts
    ---@param hp Helper                    -- helper funcs (blend, darken, …)
    overrideScheme = function(cs, p, cfg, hp) end, -- heavy customisation
  },

  -- Plugin initialiser -------------------------------------------------------
  -- Accepts the resolved opts table (including overrides) from lazy.nvim.
  config = function(_, opts)
    require("monokai-pro").setup(opts)
    -- Activate the colorscheme
    vim.cmd.colorscheme("monokai-pro")
  end,
}
